export const DEFAULT_CONSTANTS = {
  DEFAULT_EMPLOYEES_PER_PAGE: 25,
  DEFAULT_CURRENT_PAGE: 1,
  SHOW_ALL_EMPLOYEES: 9999999,
  DEFAULT_TOTAL_EMPLOYEES: 0,
  EMPLOYEE_IMAGE_API: '/base_url/api/files/employees/',
}
